Add format_html import to prevent NameError (#752)
When building a render_foo() failing to import format_html will cause:
> NameError: name 'format_html' is not defined